### ISSUE TITLE
Error in app update script

### ISSUE THREAD

**Issue by Thelch** [YunoHost-Apps/owncloud_ynh#40]
### Describe the bug

The bug appears if i try to update ownCloud (owncloud) from 5.0.0 ynh9 to 6.2.0 ynh1 (all previous updates also failes)

### Context

- Hardware: *Yunohost is running as a VM on Proxmox host*
- YunoHost version: 11.2.27
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 6.2.0~ynh1
- If upgrading, current package version: *5.0.0~ynh9*

### Steps to reproduce

   1. *Go to 'update system'*
   2. *Click on 'update application -> owncloud'*
   3. *See error*

### Logs

```
ended_at: 2024-08-05 06:32:15.138888
env:
  YNH_APP_ACTION: upgrade
  YNH_APP_BASEDIR: /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj
  YNH_APP_CURRENT_VERSION: 5.0.0~ynh9
  YNH_APP_ID: owncloud
  YNH_APP_INSTANCE_NAME: owncloud
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 6.2.0~ynh1
  YNH_APP_PACKAGING_FORMAT: '2.0'
  YNH_APP_UPGRADE_TYPE: UPGRADE_APP
  YNH_ARCH: amd64
  YNH_DEBIAN_VERSION: bullseye
  YNH_HELPERS_VERSION: '2.1'
error: Es ist ein Fehler im App-Upgrade-Skript aufgetreten
interface: api
operation: app_upgrade
parent: null
related_to:
- - app
  - owncloud
started_at: 2024-08-05 06:32:07.040186
success: false
yunohost_version: 11.2.27

============

2024-08-05 08:32:07,051: INFO - Updating sources...
2024-08-05 08:32:07,052: DEBUG - Prefetching asset main: https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 ...
2024-08-05 08:32:10,494: INFO - Updating system_user...
2024-08-05 08:32:10,521: INFO - Updating install_dir...
2024-08-05 08:32:10,527: INFO - Updating data_dir...
2024-08-05 08:32:10,532: INFO - Updating ports...
2024-08-05 08:32:10,540: INFO - Updating permissions...
2024-08-05 08:32:10,609: DEBUG - Nothing to update in LDAP
2024-08-05 08:32:10,633: DEBUG - Berechtigung 'owncloud.main' aktualisiert
2024-08-05 08:32:10,633: DEBUG - Vollständiges Log dieser Operation: '<a href="#/tools/logs/20240805-063210-user_permission_update-owncloud" style="text-decoration:underline">Aktualisiere Zugriffe für Berechtigung 'owncloud'</a>'
2024-08-05 08:32:10,698: DEBUG - Nothing to update in LDAP
2024-08-05 08:32:10,699: DEBUG - Berechtigung 'owncloud.main' aktualisiert
2024-08-05 08:32:10,723: DEBUG - Vollständiges Log dieser Operation: '<a href="#/tools/logs/20240805-063210-permission_url-owncloud" style="text-decoration:underline">Aktualisiere URL, die mit der Berechtigung 'owncloud' verknüpft ist</a>'
2024-08-05 08:32:10,781: DEBUG - Nothing to update in LDAP
2024-08-05 08:32:10,805: DEBUG - Berechtigung 'owncloud.api' aktualisiert
2024-08-05 08:32:10,806: DEBUG - Vollständiges Log dieser Operation: '<a href="#/tools/logs/20240805-063210-user_permission_update-owncloud" style="text-decoration:underline">Aktualisiere Zugriffe für Berechtigung 'owncloud'</a>'
2024-08-05 08:32:10,871: DEBUG - Nothing to update in LDAP
2024-08-05 08:32:10,871: DEBUG - Berechtigung 'owncloud.api' aktualisiert
2024-08-05 08:32:10,895: DEBUG - Vollständiges Log dieser Operation: '<a href="#/tools/logs/20240805-063210-permission_url-owncloud" style="text-decoration:underline">Aktualisiere URL, die mit der Berechtigung 'owncloud' verknüpft ist</a>'
2024-08-05 08:32:10,924: DEBUG - The permission database has been resynchronized
2024-08-05 08:32:10,967: DEBUG - SSOwat-Konfiguration neu generiert
2024-08-05 08:32:10,975: DEBUG - Executing command '['sh', '-c', '/bin/bash -x "./upgrade"  7>&1']'
2024-08-05 08:32:10,980: DEBUG - + source _common.sh
2024-08-05 08:32:10,981: DEBUG - +++ cat /etc/timezone
2024-08-05 08:32:10,981: DEBUG - ++ timezone=Europe/Berlin
2024-08-05 08:32:10,981: DEBUG - + source /usr/share/yunohost/helpers
2024-08-05 08:32:10,982: DEBUG - ++++ dirname -- /usr/share/yunohost/helpers
2024-08-05 08:32:10,982: DEBUG - +++ cd -- /usr/share/yunohost
2024-08-05 08:32:10,982: DEBUG - +++ pwd
2024-08-05 08:32:10,983: DEBUG - ++ SCRIPT_DIR=/usr/share/yunohost
2024-08-05 08:32:10,983: DEBUG - ++ YNH_HELPERS_VERSION=2.1
2024-08-05 08:32:10,984: DEBUG - ++ readonly 'XTRACE_ENABLE=set -o xtrace'
2024-08-05 08:32:10,984: DEBUG - ++ XTRACE_ENABLE='set -o xtrace'
2024-08-05 08:32:10,995: INFO - [++..................] > Stopping owncloud's systemd service...
2024-08-05 08:32:10,995: DEBUG - + ynh_systemctl --action=stop --log_path=systemd
2024-08-05 08:32:11,042: DEBUG - + service=owncloud
2024-08-05 08:32:11,042: DEBUG - + action=stop
2024-08-05 08:32:11,043: DEBUG - + wait_until=
2024-08-05 08:32:11,043: DEBUG - + length=20
2024-08-05 08:32:11,043: DEBUG - + log_path=systemd
2024-08-05 08:32:11,043: DEBUG - + timeout=60
2024-08-05 08:32:11,043: DEBUG - + ynh_in_ci_tests
2024-08-05 08:32:11,043: DEBUG - + '[' stop == stop ']'
2024-08-05 08:32:11,043: DEBUG - + systemctl is-active --quiet owncloud
2024-08-05 08:32:11,045: DEBUG - + '[' stop == reload ']'
2024-08-05 08:32:11,045: DEBUG - ++ date --utc --rfc-3339=seconds
2024-08-05 08:32:11,046: DEBUG - ++ cut -d+ -f1
2024-08-05 08:32:11,046: DEBUG - + local 'time_start=2024-08-05 06:32:11 UTC'
2024-08-05 08:32:11,047: DEBUG - + systemctl stop owncloud
2024-08-05 08:32:11,057: INFO - [##+++...............] > Ensuring downward compatibility...
2024-08-05 08:32:11,057: DEBUG - + [[ -f /var/www/owncloud/ocis.yaml ]]
2024-08-05 08:32:11,057: DEBUG - + mv /var/www/owncloud/ocis.yaml /home/yunohost.app/owncloud/config/ocis.yaml
2024-08-05 08:32:11,059: INFO - [#####+++............] > Upgrading source files...
2024-08-05 08:32:11,059: DEBUG - + ynh_setup_source --dest_dir=/var/www/owncloud --full_replace
2024-08-05 08:32:11,092: DEBUG - + keep=
2024-08-05 08:32:11,092: DEBUG - + full_replace=1
2024-08-05 08:32:11,092: DEBUG - + source_id=main
2024-08-05 08:32:11,092: DEBUG - ++ ynh_read_manifest 'resources.sources["main"]'
2024-08-05 08:32:11,092: DEBUG - ++ cat /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/manifest.toml
2024-08-05 08:32:11,092: DEBUG - ++ toml_to_json
2024-08-05 08:32:11,093: DEBUG - ++ jq '.resources.sources["main"]' --raw-output
2024-08-05 08:32:11,093: DEBUG - ++ python3 -c 'import toml, json, sys; print(json.dumps(toml.load(sys.stdin)))'
2024-08-05 08:32:11,120: DEBUG - + local 'sources_json={
2024-08-05 08:32:11,120: DEBUG -   "amd64": {
2024-08-05 08:32:11,120: DEBUG -     "url": "https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64",
2024-08-05 08:32:11,120: DEBUG -     "sha256": "3f033234ecc5a73ff7cecb671699f34e494cf45f405068cb848f1aee2014118a"
2024-08-05 08:32:11,120: DEBUG -   },
2024-08-05 08:32:11,121: DEBUG -   "arm64": {
2024-08-05 08:32:11,121: DEBUG -     "url": "https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-arm64",
2024-08-05 08:32:11,121: DEBUG -     "sha256": "ef86baa55bfe59357d61813317d2f604714680752716344b0992da9526eb5e69"
2024-08-05 08:32:11,121: DEBUG -   },
2024-08-05 08:32:11,121: DEBUG -   "armhf": {
2024-08-05 08:32:11,121: DEBUG -     "url": "https://github.com/owncloud/ocis/releases/download/v6.1.0/ocis-6.1.0-linux-arm",
2024-08-05 08:32:11,121: DEBUG -     "sha256": "de6fcb0581fa611522693157ea99317e08e38b986b9e7cad67c11e56cff82dae"
2024-08-05 08:32:11,121: DEBUG -   },
2024-08-05 08:32:11,121: DEBUG -   "i386": {
2024-08-05 08:32:11,121: DEBUG -     "url": "https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-386",
2024-08-05 08:32:11,121: DEBUG -     "sha256": "06988556f8c720ac71367ffaf607a2509db0cd6e12e72cf413dd22d5fc858c59"
2024-08-05 08:32:11,121: DEBUG -   },
2024-08-05 08:32:11,121: DEBUG -   "in_subdir": false,
2024-08-05 08:32:11,122: DEBUG -   "rename": "ocis",
2024-08-05 08:32:11,122: DEBUG -   "autoupdate": {
2024-08-05 08:32:11,122: DEBUG -     "strategy": "latest_github_release",
2024-08-05 08:32:11,122: DEBUG -     "asset": {
2024-08-05 08:32:11,122: DEBUG -       "amd64": "^ocis-.*-linux-amd64$",
2024-08-05 08:32:11,122: DEBUG -       "arm64": "^ocis-.*-linux-arm64$",
2024-08-05 08:32:11,122: DEBUG -       "i386": "^ocis-.*-linux-386$"
2024-08-05 08:32:11,122: DEBUG -     }
2024-08-05 08:32:11,122: DEBUG -   }
2024-08-05 08:32:11,122: DEBUG - }'
2024-08-05 08:32:11,122: DEBUG - + jq -re .url
2024-08-05 08:32:11,145: DEBUG - null
2024-08-05 08:32:11,145: DEBUG - + local arch_prefix=.amd64
2024-08-05 08:32:11,172: DEBUG - + local src_url=https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64
2024-08-05 08:32:11,197: DEBUG - + local src_sum=3f033234ecc5a73ff7cecb671699f34e494cf45f405068cb848f1aee2014118a
2024-08-05 08:32:11,222: DEBUG - + local src_format=
2024-08-05 08:32:11,246: DEBUG - + local src_in_subdir=false
2024-08-05 08:32:11,247: DEBUG - + src_in_subdir=false
2024-08-05 08:32:11,271: DEBUG - + local src_extract=
2024-08-05 08:32:11,296: DEBUG - + local src_platform=
2024-08-05 08:32:11,321: DEBUG - + local src_rename=ocis
2024-08-05 08:32:11,321: DEBUG - + [[ -n https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 ]]
2024-08-05 08:32:11,321: DEBUG - + [[ -n 3f033234ecc5a73ff7cecb671699f34e494cf45f405068cb848f1aee2014118a ]]
2024-08-05 08:32:11,321: DEBUG - + [[ -z '' ]]
2024-08-05 08:32:11,321: DEBUG - + [[ https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 =~ ^.*\.zip$ ]]
2024-08-05 08:32:11,322: DEBUG - + [[ https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 =~ ^.*/zipball/.*$ ]]
2024-08-05 08:32:11,322: DEBUG - + [[ https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 =~ ^.*\.tar\.gz$ ]]
2024-08-05 08:32:11,322: DEBUG - + [[ https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 =~ ^.*\.tgz$ ]]
2024-08-05 08:32:11,322: DEBUG - + [[ https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 =~ ^.*/tar\.gz/.*$ ]]
2024-08-05 08:32:11,322: DEBUG - + [[ https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 =~ ^.*/tarball/.*$ ]]
2024-08-05 08:32:11,322: DEBUG - + [[ https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 =~ ^.*\.tar\.xz$ ]]
2024-08-05 08:32:11,322: DEBUG - + [[ https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 =~ ^.*\.tar\.bz2$ ]]
2024-08-05 08:32:11,322: DEBUG - + [[ https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 =~ ^.*\.tar$ ]]
2024-08-05 08:32:11,322: DEBUG - + [[ -z '' ]]
2024-08-05 08:32:11,322: DEBUG - + src_extract=false
2024-08-05 08:32:11,322: DEBUG - + src_format=tar.gz
2024-08-05 08:32:11,323: DEBUG - ++ echo tar.gz
2024-08-05 08:32:11,323: DEBUG - ++ tr '[:upper:]' '[:lower:]'
2024-08-05 08:32:11,323: DEBUG - + src_format=tar.gz
2024-08-05 08:32:11,323: DEBUG - + src_extract=false
2024-08-05 08:32:11,323: DEBUG - + [[ false != \t\r\u\e ]]
2024-08-05 08:32:11,323: DEBUG - + [[ false != \f\a\l\s\e ]]
2024-08-05 08:32:11,323: DEBUG - ++ dirname /var/cache/yunohost/download/owncloud/main
2024-08-05 08:32:11,323: DEBUG - + mkdir -p /var/cache/yunohost/download/owncloud
2024-08-05 08:32:11,324: DEBUG - + src_filename=/var/cache/yunohost/download/owncloud/main
2024-08-05 08:32:11,325: DEBUG - + '[' tar.gz = docker ']'
2024-08-05 08:32:11,325: DEBUG - + '[' -n https://github.com/owncloud/ocis/releases/download/v6.2.0/ocis-6.2.0-linux-amd64 ']'
2024-08-05 08:32:11,325: DEBUG - + '[' -e /var/cache/yunohost/download/owncloud/main ']'
2024-08-05 08:32:11,325: DEBUG - + sha256sum --check --status
2024-08-05 08:32:11,745: DEBUG - + '[' '!' -e /var/cache/yunohost/download/owncloud/main ']'
2024-08-05 08:32:11,745: DEBUG - + sha256sum --check --status
2024-08-05 08:32:12,161: DEBUG - + rm -rf /var/cache/yunohost/files_to_keep_during_setup_source/
2024-08-05 08:32:12,162: DEBUG - + '[' -n '' ']'
2024-08-05 08:32:12,162: DEBUG - + ynh_safe_rm /var/www/owncloud
2024-08-05 08:32:12,162: DEBUG - + local target=/var/www/owncloud
2024-08-05 08:32:12,178: DEBUG - + mkdir --parents /var/www/owncloud
2024-08-05 08:32:12,179: DEBUG - + [[ false == \f\a\l\s\e ]]
2024-08-05 08:32:12,179: DEBUG - + [[ -z ocis ]]
2024-08-05 08:32:12,179: DEBUG - + mv /var/cache/yunohost/download/owncloud/main /var/www/owncloud/ocis
2024-08-05 08:32:12,180: DEBUG - ++ realpath /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/patches/main
2024-08-05 08:32:12,183: WARNING - realpath: /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/patches/main: Datei oder Verzeichnis nicht gefunden
2024-08-05 08:32:12,184: DEBUG - + local patches_folder=
2024-08-05 08:32:12,184: DEBUG - + '[' -d '' ']'
2024-08-05 08:32:12,184: DEBUG - + '[' -n '' ']'
2024-08-05 08:32:12,184: DEBUG - + rm -rf /var/cache/yunohost/files_to_keep_during_setup_source/
2024-08-05 08:32:12,184: DEBUG - + '[' -n /var/www/owncloud ']'
2024-08-05 08:32:12,184: DEBUG - + '[' /var/www/owncloud == /var/www/owncloud ']'
2024-08-05 08:32:12,185: DEBUG - + _ynh_apply_default_permissions /var/www/owncloud
2024-08-05 08:32:12,185: DEBUG - + local target=/var/www/owncloud
2024-08-05 08:32:12,185: DEBUG - + ynh_system_user_exists --username=owncloud
2024-08-05 08:32:12,189: DEBUG - + getent passwd owncloud
2024-08-05 08:32:12,192: DEBUG - + '[' -f /var/www/owncloud ']'
2024-08-05 08:32:12,192: DEBUG - + '[' /var/www/owncloud == /var/www/owncloud ']'
2024-08-05 08:32:12,192: DEBUG - ++ ynh_read_manifest resources.install_dir.group
2024-08-05 08:32:12,192: DEBUG - ++ sed s/null//g
2024-08-05 08:32:12,193: DEBUG - ++ toml_to_json
2024-08-05 08:32:12,193: DEBUG - ++ python3 -c 'import toml, json, sys; print(json.dumps(toml.load(sys.stdin)))'
2024-08-05 08:32:12,193: DEBUG - ++ jq .resources.install_dir.group --raw-output
2024-08-05 08:32:12,193: DEBUG - ++ cut -f1 -d:
2024-08-05 08:32:12,193: DEBUG - ++ cat /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/manifest.toml
2024-08-05 08:32:12,194: DEBUG - ++ sed s/__APP__/owncloud/g
2024-08-05 08:32:12,233: DEBUG - + local group=
2024-08-05 08:32:12,233: DEBUG - + [[ -z '' ]]
2024-08-05 08:32:12,233: DEBUG - + grep -q '^\s*alias\s\|^\s*root\s' /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/nginx.conf
2024-08-05 08:32:12,234: DEBUG - + group=owncloud
2024-08-05 08:32:12,235: DEBUG - + chmod -R u=rwX,g=rX,o=--- /var/www/owncloud
2024-08-05 08:32:12,235: DEBUG - + chown -R owncloud:owncloud /var/www/owncloud
2024-08-05 08:32:12,238: DEBUG - + return
2024-08-05 08:32:12,238: DEBUG - + chmod -R o-rwx /var/www/owncloud
2024-08-05 08:32:12,238: DEBUG - + chown -R owncloud:www-data /var/www/owncloud
2024-08-05 08:32:12,241: DEBUG - + chmod +x /var/www/owncloud/ocis
2024-08-05 08:32:12,243: INFO - [########+++.........] > Upgrading system configurations related to owncloud...
2024-08-05 08:32:12,243: DEBUG - + ynh_config_add_nginx
2024-08-05 08:32:12,243: DEBUG - + local finalnginxconf=/etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,243: DEBUG - + ynh_config_add --template=nginx.conf --destination=/etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,275: DEBUG - + jinja=0
2024-08-05 08:32:12,275: DEBUG - + '[' -f /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/nginx.conf ']'
2024-08-05 08:32:12,275: DEBUG - + template_path=/var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/nginx.conf
2024-08-05 08:32:12,275: DEBUG - + ynh_backup_if_checksum_is_different /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,323: DEBUG - + touch /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,324: DEBUG - + chmod 640 /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,325: DEBUG - + _ynh_apply_default_permissions /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,325: DEBUG - + local target=/etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,325: DEBUG - + ynh_system_user_exists --username=owncloud
2024-08-05 08:32:12,333: DEBUG - + getent passwd owncloud
2024-08-05 08:32:12,335: DEBUG - + '[' -f /etc/nginx/conf.d/domain2.tld.d/owncloud.conf ']'
2024-08-05 08:32:12,335: DEBUG - + is_in_dir /etc/nginx/conf.d/domain2.tld.d/owncloud.conf /var/www/owncloud
2024-08-05 08:32:12,335: DEBUG - + '[' -n /var/www/owncloud ']'
2024-08-05 08:32:12,335: DEBUG - ++ realpath /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,336: DEBUG - + local child=/etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,337: DEBUG - ++ realpath /var/www/owncloud
2024-08-05 08:32:12,338: DEBUG - + local parent=/var/www/owncloud
2024-08-05 08:32:12,338: DEBUG - + [[ /etc/nginx/conf.d/domain2.tld.d/owncloud.conf =~ ^/var/www/owncloud ]]
2024-08-05 08:32:12,338: DEBUG - + is_in_dir /etc/nginx/conf.d/domain2.tld.d/owncloud.conf /home/yunohost.app/owncloud
2024-08-05 08:32:12,338: DEBUG - + '[' -n /home/yunohost.app/owncloud ']'
2024-08-05 08:32:12,339: DEBUG - ++ realpath /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,340: DEBUG - + local child=/etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,340: DEBUG - ++ realpath /home/yunohost.app/owncloud
2024-08-05 08:32:12,341: DEBUG - + local parent=/home/yunohost.app/owncloud
2024-08-05 08:32:12,341: DEBUG - + [[ /etc/nginx/conf.d/domain2.tld.d/owncloud.conf =~ ^/home/yunohost.app/owncloud ]]
2024-08-05 08:32:12,341: DEBUG - + is_in_dir /etc/nginx/conf.d/domain2.tld.d/owncloud.conf /etc/owncloud
2024-08-05 08:32:12,342: DEBUG - + '[' -n /etc/owncloud ']'
2024-08-05 08:32:12,342: DEBUG - ++ realpath /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,343: DEBUG - + local child=/etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,343: DEBUG - ++ realpath /etc/owncloud
2024-08-05 08:32:12,344: DEBUG - + local parent=/etc/owncloud
2024-08-05 08:32:12,344: DEBUG - + [[ /etc/nginx/conf.d/domain2.tld.d/owncloud.conf =~ ^/etc/owncloud ]]
2024-08-05 08:32:12,344: DEBUG - + '[' /etc/nginx/conf.d/domain2.tld.d/owncloud.conf == /var/www/owncloud ']'
2024-08-05 08:32:12,345: DEBUG - + chmod 400 /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,345: DEBUG - + chown root:root /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,350: DEBUG - + [[ 0 == 1 ]]
2024-08-05 08:32:12,350: DEBUG - + cp -f /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/nginx.conf /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,351: DEBUG - + _ynh_replace_vars /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,352: DEBUG - + local file=/etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,352: DEBUG - ++ grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,352: DEBUG - ++ sort --unique
2024-08-05 08:32:12,352: DEBUG - ++ sed 's@__\([^.]*\)__@\L\1@g'
2024-08-05 08:32:12,354: DEBUG - + uniques_vars=('path' 'port')
2024-08-05 08:32:12,359: DEBUG - + ynh_store_file_checksum /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,427: DEBUG - + '[' / '!=' / ']'
2024-08-05 08:32:12,427: DEBUG - + ynh_replace '--match=^#root_path_only' --replace= --file=/etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,470: DEBUG - + ynh_store_file_checksum /etc/nginx/conf.d/domain2.tld.d/owncloud.conf
2024-08-05 08:32:12,536: DEBUG - + ynh_systemctl --service=nginx --action=reload
2024-08-05 08:32:12,586: DEBUG - + service=nginx
2024-08-05 08:32:12,587: DEBUG - + action=reload
2024-08-05 08:32:12,587: DEBUG - + wait_until=
2024-08-05 08:32:12,587: DEBUG - + length=20
2024-08-05 08:32:12,587: DEBUG - + log_path=/var/log/nginx/nginx.log
2024-08-05 08:32:12,587: DEBUG - + timeout=60
2024-08-05 08:32:12,587: DEBUG - + ynh_in_ci_tests
2024-08-05 08:32:12,587: DEBUG - + '[' reload == stop ']'
2024-08-05 08:32:12,587: DEBUG - + '[' reload == reload ']'
2024-08-05 08:32:12,587: DEBUG - + action=reload-or-restart
2024-08-05 08:32:12,588: DEBUG - ++ date --utc --rfc-3339=seconds
2024-08-05 08:32:12,588: DEBUG - ++ cut -d+ -f1
2024-08-05 08:32:12,588: DEBUG - + local 'time_start=2024-08-05 06:32:12 UTC'
2024-08-05 08:32:12,588: DEBUG - + systemctl reload-or-restart nginx
2024-08-05 08:32:12,632: DEBUG - + ynh_config_add_systemd
2024-08-05 08:32:12,634: DEBUG - + return
2024-08-05 08:32:12,634: DEBUG - + service=owncloud
2024-08-05 08:32:12,635: DEBUG - + template=systemd.service
2024-08-05 08:32:12,635: DEBUG - + ynh_config_add --template=systemd.service --destination=/etc/systemd/system/owncloud.service
2024-08-05 08:32:12,661: DEBUG - + jinja=0
2024-08-05 08:32:12,662: DEBUG - + '[' -f /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/systemd.service ']'
2024-08-05 08:32:12,662: DEBUG - + template_path=/var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/systemd.service
2024-08-05 08:32:12,662: DEBUG - + ynh_backup_if_checksum_is_different /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,711: DEBUG - + touch /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,711: DEBUG - + chmod 640 /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,712: DEBUG - + _ynh_apply_default_permissions /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,712: DEBUG - + local target=/etc/systemd/system/owncloud.service
2024-08-05 08:32:12,712: DEBUG - + ynh_system_user_exists --username=owncloud
2024-08-05 08:32:12,720: DEBUG - + getent passwd owncloud
2024-08-05 08:32:12,721: DEBUG - + '[' -f /etc/systemd/system/owncloud.service ']'
2024-08-05 08:32:12,721: DEBUG - + is_in_dir /etc/systemd/system/owncloud.service /var/www/owncloud
2024-08-05 08:32:12,721: DEBUG - + '[' -n /var/www/owncloud ']'
2024-08-05 08:32:12,721: DEBUG - ++ realpath /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,722: DEBUG - + local child=/etc/systemd/system/owncloud.service
2024-08-05 08:32:12,723: DEBUG - ++ realpath /var/www/owncloud
2024-08-05 08:32:12,723: DEBUG - + local parent=/var/www/owncloud
2024-08-05 08:32:12,724: DEBUG - + [[ /etc/systemd/system/owncloud.service =~ ^/var/www/owncloud ]]
2024-08-05 08:32:12,724: DEBUG - + is_in_dir /etc/systemd/system/owncloud.service /home/yunohost.app/owncloud
2024-08-05 08:32:12,724: DEBUG - + '[' -n /home/yunohost.app/owncloud ']'
2024-08-05 08:32:12,724: DEBUG - ++ realpath /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,725: DEBUG - + local child=/etc/systemd/system/owncloud.service
2024-08-05 08:32:12,725: DEBUG - ++ realpath /home/yunohost.app/owncloud
2024-08-05 08:32:12,726: DEBUG - + local parent=/home/yunohost.app/owncloud
2024-08-05 08:32:12,726: DEBUG - + [[ /etc/systemd/system/owncloud.service =~ ^/home/yunohost.app/owncloud ]]
2024-08-05 08:32:12,726: DEBUG - + is_in_dir /etc/systemd/system/owncloud.service /etc/owncloud
2024-08-05 08:32:12,726: DEBUG - + '[' -n /etc/owncloud ']'
2024-08-05 08:32:12,726: DEBUG - ++ realpath /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,727: DEBUG - + local child=/etc/systemd/system/owncloud.service
2024-08-05 08:32:12,728: DEBUG - ++ realpath /etc/owncloud
2024-08-05 08:32:12,728: DEBUG - + local parent=/etc/owncloud
2024-08-05 08:32:12,729: DEBUG - + [[ /etc/systemd/system/owncloud.service =~ ^/etc/owncloud ]]
2024-08-05 08:32:12,729: DEBUG - + '[' /etc/systemd/system/owncloud.service == /var/www/owncloud ']'
2024-08-05 08:32:12,729: DEBUG - + chmod 400 /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,729: DEBUG - + chown root:root /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,730: DEBUG - + [[ 0 == 1 ]]
2024-08-05 08:32:12,731: DEBUG - + cp -f /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/systemd.service /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,732: DEBUG - + _ynh_replace_vars /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,732: DEBUG - + local file=/etc/systemd/system/owncloud.service
2024-08-05 08:32:12,732: DEBUG - ++ grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,732: DEBUG - ++ sort --unique
2024-08-05 08:32:12,732: DEBUG - ++ sed 's@__\([^.]*\)__@\L\1@g'
2024-08-05 08:32:12,734: DEBUG - + uniques_vars=('app' 'data_dir' 'install_dir')
2024-08-05 08:32:12,738: DEBUG - + ynh_store_file_checksum /etc/systemd/system/owncloud.service
2024-08-05 08:32:12,800: DEBUG - + systemctl enable owncloud --quiet
2024-08-05 08:32:12,964: DEBUG - + systemctl daemon-reload
2024-08-05 08:32:13,143: DEBUG - + yunohost service add owncloud '--description=File sharing platform' --log=/var/log/owncloud/owncloud.log
2024-08-05 08:32:13,315: DEBUG - Der Dienst 'owncloud' wurde erfolgreich hinzugefügt
2024-08-05 08:32:13,332: INFO - [###########+++......] > Adding owncloud's configuration...
2024-08-05 08:32:13,333: DEBUG - + ynh_config_add --template=.env --destination=/var/www/owncloud/ocis.env
2024-08-05 08:32:13,362: DEBUG - + jinja=0
2024-08-05 08:32:13,362: DEBUG - + '[' -f /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/.env ']'
2024-08-05 08:32:13,362: DEBUG - + template_path=/var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/.env
2024-08-05 08:32:13,362: DEBUG - + ynh_backup_if_checksum_is_different /var/www/owncloud/ocis.env
2024-08-05 08:32:13,407: DEBUG - + touch /var/www/owncloud/ocis.env
2024-08-05 08:32:13,407: DEBUG - + chmod 640 /var/www/owncloud/ocis.env
2024-08-05 08:32:13,408: DEBUG - + _ynh_apply_default_permissions /var/www/owncloud/ocis.env
2024-08-05 08:32:13,408: DEBUG - + local target=/var/www/owncloud/ocis.env
2024-08-05 08:32:13,408: DEBUG - + ynh_system_user_exists --username=owncloud
2024-08-05 08:32:13,416: DEBUG - + getent passwd owncloud
2024-08-05 08:32:13,417: DEBUG - + '[' -f /var/www/owncloud/ocis.env ']'
2024-08-05 08:32:13,417: DEBUG - + is_in_dir /var/www/owncloud/ocis.env /var/www/owncloud
2024-08-05 08:32:13,417: DEBUG - + '[' -n /var/www/owncloud ']'
2024-08-05 08:32:13,417: DEBUG - ++ realpath /var/www/owncloud/ocis.env
2024-08-05 08:32:13,418: DEBUG - + local child=/var/www/owncloud/ocis.env
2024-08-05 08:32:13,419: DEBUG - ++ realpath /var/www/owncloud
2024-08-05 08:32:13,420: DEBUG - + local parent=/var/www/owncloud
2024-08-05 08:32:13,420: DEBUG - + [[ /var/www/owncloud/ocis.env =~ ^/var/www/owncloud ]]
2024-08-05 08:32:13,420: DEBUG - + chmod 600 /var/www/owncloud/ocis.env
2024-08-05 08:32:13,421: DEBUG - + chown owncloud:owncloud /var/www/owncloud/ocis.env
2024-08-05 08:32:13,422: DEBUG - + return
2024-08-05 08:32:13,422: DEBUG - + [[ 0 == 1 ]]
2024-08-05 08:32:13,422: DEBUG - + cp -f /var/cache/yunohost/app_tmp_work_dirs/app_ye9l65rj/conf/.env /var/www/owncloud/ocis.env
2024-08-05 08:32:13,423: DEBUG - + _ynh_replace_vars /var/www/owncloud/ocis.env
2024-08-05 08:32:13,423: DEBUG - + local file=/var/www/owncloud/ocis.env
2024-08-05 08:32:13,424: DEBUG - ++ grep -oP '__[A-Z0-9]+?[A-Z0-9_]*?[A-Z0-9]*?__' /var/www/owncloud/ocis.env
2024-08-05 08:32:13,424: DEBUG - ++ sort --unique
2024-08-05 08:32:13,424: DEBUG - ++ sed 's@__\([^.]*\)__@\L\1@g'
2024-08-05 08:32:13,426: DEBUG - + uniques_vars=('data_dir' 'domain' 'language' 'port' 'timezone')
2024-08-05 08:32:13,432: DEBUG - + ynh_store_file_checksum /var/www/owncloud/ocis.env
2024-08-05 08:32:13,496: DEBUG - + chmod 400 /var/www/owncloud/ocis.env
2024-08-05 08:32:13,497: DEBUG - + chown owncloud:owncloud /var/www/owncloud/ocis.env
2024-08-05 08:32:13,499: INFO - [##############+++...] > Starting owncloud's systemd service...
2024-08-05 08:32:13,499: DEBUG - + ynh_systemctl --action=start --log_path=systemd
2024-08-05 08:32:13,548: DEBUG - + service=owncloud
2024-08-05 08:32:13,549: DEBUG - + action=start
2024-08-05 08:32:13,549: DEBUG - + wait_until=
2024-08-05 08:32:13,549: DEBUG - + length=20
2024-08-05 08:32:13,549: DEBUG - + log_path=systemd
2024-08-05 08:32:13,549: DEBUG - + timeout=60
2024-08-05 08:32:13,549: DEBUG - + ynh_in_ci_tests
2024-08-05 08:32:13,549: DEBUG - + '[' start == stop ']'
2024-08-05 08:32:13,550: DEBUG - + '[' start == reload ']'
2024-08-05 08:32:13,550: DEBUG - ++ date --utc --rfc-3339=seconds
2024-08-05 08:32:13,550: DEBUG - ++ cut -d+ -f1
2024-08-05 08:32:13,550: DEBUG - + local 'time_start=2024-08-05 06:32:13 UTC'
2024-08-05 08:32:13,550: DEBUG - + systemctl start owncloud
2024-08-05 08:32:13,555: WARNING - Job for owncloud.service failed because of unavailable resources or another system error.
2024-08-05 08:32:13,555: WARNING - See "systemctl status owncloud.service" and "journalctl -xe" for details.
2024-08-05 08:32:13,556: DEBUG - + journalctl --quiet --no-hostname --no-pager --lines=20 --unit=owncloud
2024-08-05 08:32:13,634: WARNING - Jul 18 09:25:50 systemd[1]: owncloud.service: Scheduled restart job, restart counter is at 5.
2024-08-05 08:32:13,635: WARNING - Jul 18 09:25:50 systemd[1]: Stopped ownCloud: Infinite Scale server.
2024-08-05 08:32:13,635: WARNING - Jul 18 09:25:50 systemd[1]: owncloud.service: Start request repeated too quickly.
2024-08-05 08:32:13,635: WARNING - Jul 18 09:25:50 systemd[1]: owncloud.service: Failed with result 'resources'.
2024-08-05 08:32:13,636: WARNING - Jul 18 09:25:50 systemd[1]: Failed to start ownCloud: Infinite Scale server.
2024-08-05 08:32:13,636: WARNING - Jul 18 09:25:57 systemd[1]: Started ownCloud: Infinite Scale server.
2024-08-05 08:32:13,636: WARNING - Jul 18 09:25:57 ocis[920920]: {"level":"warn","service":"nats","time":"2024-07-18T09:25:57+02:00","message":"Filestore [main-queue] Stream state encountered internal inconsistency on recover"}
2024-08-05 08:32:13,637: WARNING - Jul 18 09:26:03 ocis[920920]: {"level":"warn","service":"storage-system","pkg":"rhttp","time":"2024-07-18T09:26:03+02:00","message":"missing or incomplete nats configuration. Events will not be published."}
2024-08-05 08:32:13,637: WARNING - Jul 18 09:26:05 ocis[920920]: {"level":"warn","service":"ocm","pkg":"rhttp","time":"2024-07-18T09:26:05+02:00","message":"missing or incomplete nats configuration. Events will not be published."}
2024-08-05 08:32:13,637: WARNING - Jul 18 09:26:05 ocis[920920]: {"level":"warn","service":"proxy","time":"2024-07-18T09:26:05+02:00","message":"No tls certificate provided, using a generated one"}
2024-08-05 08:32:13,637: WARNING - Jul 18 09:26:05 ocis[920920]: {"level":"warn","service":"idp","kid":"private-key","path":"/home/yunohost.app/owncloud/idp/private-key.pem","time":"2024-07-18T09:26:05+02:00","message":"skipped as signer with same kid already loaded"}
2024-08-05 08:32:13,638: WARNING - Aug 05 08:32:11 systemd[1]: Stopping ownCloud: Infinite Scale server...
2024-08-05 08:32:13,638: WARNING - Aug 05 08:32:11 ocis[920920]: {"level":"warn","service":"idm","signal":15,"time":"2024-08-05T08:32:11+02:00","message":"received signal"}
2024-08-05 08:32:13,638: WARNING - Aug 05 08:32:11 systemd[1]: owncloud.service: Succeeded.
2024-08-05 08:32:13,638: WARNING - Aug 05 08:32:11 systemd[1]: Stopped ownCloud: Infinite Scale server.
2024-08-05 08:32:13,639: WARNING - Aug 05 08:32:11 systemd[1]: owncloud.service: Consumed 1h 10min 4.095s CPU time.
2024-08-05 08:32:13,639: WARNING - Aug 05 08:32:13 systemd[1]: owncloud.service: Failed to load environment files: No such file or directory
2024-08-05 08:32:13,639: WARNING - Aug 05 08:32:13 systemd[1]: owncloud.service: Failed to run 'start' task: No such file or directory
2024-08-05 08:32:13,639: WARNING - Aug 05 08:32:13 systemd[1]: owncloud.service: Failed with result 'resources'.
2024-08-05 08:32:13,639: WARNING - Aug 05 08:32:13 systemd[1]: Failed to start ownCloud: Infinite Scale server.
2024-08-05 08:32:13,640: DEBUG - + '[' -e systemd ']'
2024-08-05 08:32:13,640: DEBUG - + _ynh_clean_check_starting
2024-08-05 08:32:13,640: DEBUG - + '[' -n '' ']'
2024-08-05 08:32:13,640: DEBUG - + '[' -n '' ']'
2024-08-05 08:32:13,640: DEBUG - + return 1
2024-08-05 08:32:13,640: DEBUG - + ynh_exit_properly
2024-08-05 08:32:13,640: DEBUG - + [[ upgrade =~ ^install$|^upgrade$|^restore$ ]]
2024-08-05 08:32:15,138: ERROR - owncloud konnte nicht aktualisiert werden: Es ist ein Fehler im App-Upgrade-Skript aufgetreten
```

**Comment by ericgaspar** [comment]
this should be fixed by now. Tell me

**Comment by Thelch** [comment]
i tried it with every version and it is still not working.

Today i migrated to yunohost 12.0.7 and tried to upgrade owncloud to 7.0.0~ynh1 

Upgrade is running but the service is still not starting:

`LOGFILE: journalctl
Nov 26 10:03:14 ocis[2415862]: {"level":"warn","service":"proxy","time":"2024-11-26T10:03:14+01:00","message":"basic auth enabled, use only for testing or development"}
Nov 26 10:03:14 ocis[2415862]: {"level":"warn","service":"proxy","time":"2024-11-26T10:03:14+01:00","message":"No tls certificate provided, using a generated one"}
Nov 26 10:03:14 ocis[2415862]: {"level":"warn","service":"idp","kid":"private-key","path":"/home/yunohost.app/owncloud/idp/private-key.pem","time":"2024-11-26T10:03:14+01:00","message":"skipped as signer with same kid already loaded"}
Nov 26 10:03:14 ocis[2415862]: The service account id has not been configured for ocm. Make sure your /home/yunohost.app/owncloud/config/ config contains the proper values (e.g. by using 'ocis init --diff' and applying the patch or setting a value manually in the config/corresponding environment variable).
Nov 26 10:03:14 systemd[1]: owncloud.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 10:03:14 systemd[1]: owncloud.service: Failed with result 'exit-code'.
Nov 26 10:03:14 systemd[1]: owncloud.service: Scheduled restart job, restart counter is at 1.
Nov 26 10:03:14 systemd[1]: Stopped owncloud.service - ownCloud: Infinite Scale server.
Nov 26 10:03:14 systemd[1]: Started owncloud.service - ownCloud: Infinite Scale server.
Nov 26 10:03:14 ocis[2415921]: {"level":"warn","service":"nats","time":"2024-11-26T10:03:14+01:00","message":"Filestore [KV_service-registry] Stream state outdated, last block has additional entries, will rebuild"}
Nov 26 10:03:14 ocis[2415921]: {"level":"warn","service":"nats","time":"2024-11-26T10:03:14+01:00","message":"Filestore [KV_service-registry] Recovering stream state from index errored: prior state file"}
Nov 26 10:03:15 ocis[2415921]: The service account id has not been configured for ocm. Make sure your /home/yunohost.app/owncloud/config/ config contains the proper values (e.g. by using 'ocis init --diff' and applying the patch or setting a value manually in the config/corresponding environment variable).
Nov 26 10:03:15 systemd[1]: owncloud.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 10:03:15 systemd[1]: owncloud.service: Failed with result 'exit-code'.
Nov 26 10:03:15 systemd[1]: owncloud.service: Scheduled restart job, restart counter is at 2.
Nov 26 10:03:15 systemd[1]: Stopped owncloud.service - ownCloud: Infinite Scale server.
Nov 26 10:03:15 systemd[1]: Started owncloud.service - ownCloud: Infinite Scale server.
Nov 26 10:03:15 ocis[2415932]: {"level":"warn","service":"nats","time":"2024-11-26T10:03:15+01:00","message":"Filestore [KV_service-registry] Stream state outdated, last block has additional entries, will rebuild"}
Nov 26 10:03:15 ocis[2415932]: {"level":"warn","service":"nats","time":"2024-11-26T10:03:15+01:00","message":"Filestore [KV_service-registry] Recovering stream state from index errored: prior state file"}
Nov 26 10:03:16 ocis[2415932]: {"level":"warn","service":"idp","kid":"private-key","path":"/home/yunohost.app/owncloud/idp/private-key.pem","time":"2024-11-26T10:03:16+01:00","message":"skipped as signer with same kid already loaded"}
Nov 26 10:03:16 ocis[2415932]: The service account id has not been configured for ocm. Make sure your /home/yunohost.app/owncloud/config/ config contains the proper values (e.g. by using 'ocis init --diff' and applying the patch or setting a value manually in the config/corresponding environment variable).
Nov 26 10:03:16 systemd[1]: owncloud.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 10:03:16 systemd[1]: owncloud.service: Failed with result 'exit-code'.
Nov 26 10:03:16 systemd[1]: owncloud.service: Scheduled restart job, restart counter is at 3.
Nov 26 10:03:16 systemd[1]: Stopped owncloud.service - ownCloud: Infinite Scale server.
Nov 26 10:03:16 systemd[1]: Started owncloud.service - ownCloud: Infinite Scale server.
Nov 26 10:03:16 ocis[2415943]: {"level":"warn","service":"nats","time":"2024-11-26T10:03:16+01:00","message":"Filestore [KV_service-registry] Stream state outdated, last block has additional entries, will rebuild"}
Nov 26 10:03:16 ocis[2415943]: {"level":"warn","service":"nats","time":"2024-11-26T10:03:16+01:00","message":"Filestore [KV_service-registry] Recovering stream state from index errored: prior state file"}
Nov 26 10:03:17 ocis[2415943]: {"level":"warn","service":"idp","kid":"private-key","path":"/home/yunohost.app/owncloud/idp/private-key.pem","time":"2024-11-26T10:03:17+01:00","message":"skipped as signer with same kid already loaded"}
Nov 26 10:03:17 ocis[2415943]: {"level":"warn","service":"proxy","time":"2024-11-26T10:03:17+01:00","message":"basic auth enabled, use only for testing or development"}
Nov 26 10:03:17 ocis[2415943]: The service account id has not been configured for ocm. Make sure your /home/yunohost.app/owncloud/config/ config contains the proper values (e.g. by using 'ocis init --diff' and applying the patch or setting a value manually in the config/corresponding environment variable).
Nov 26 10:03:17 ocis[2415943]: {"level":"warn","service":"proxy","time":"2024-11-26T10:03:17+01:00","message":"No tls certificate provided, using a generated one"}
Nov 26 10:03:17 systemd[1]: owncloud.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 10:03:17 systemd[1]: owncloud.service: Failed with result 'exit-code'.
Nov 26 10:03:18 systemd[1]: owncloud.service: Scheduled restart job, restart counter is at 4.
Nov 26 10:03:18 systemd[1]: Stopped owncloud.service - ownCloud: Infinite Scale server.
Nov 26 10:03:18 systemd[1]: Started owncloud.service - ownCloud: Infinite Scale server.
Nov 26 10:03:18 ocis[2415985]: {"level":"warn","service":"nats","time":"2024-11-26T10:03:18+01:00","message":"Filestore [KV_service-registry] Stream state outdated, last block has additional entries, will rebuild"}
Nov 26 10:03:18 ocis[2415985]: {"level":"warn","service":"nats","time":"2024-11-26T10:03:18+01:00","message":"Filestore [KV_service-registry] Recovering stream state from index errored: prior state file"}
Nov 26 10:03:18 ocis[2415985]: {"level":"warn","service":"storage-system","pkg":"rhttp","time":"2024-11-26T10:03:18+01:00","message":"missing or incomplete nats configuration. Events will not be published."}
Nov 26 10:03:18 ocis[2415985]: {"level":"warn","service":"proxy","time":"2024-11-26T10:03:18+01:00","message":"basic auth enabled, use only for testing or development"}
Nov 26 10:03:18 ocis[2415985]: {"level":"warn","service":"proxy","time":"2024-11-26T10:03:18+01:00","message":"No tls certificate provided, using a generated one"}
Nov 26 10:03:18 ocis[2415985]: The service account id has not been configured for ocm. Make sure your /home/yunohost.app/owncloud/config/ config contains the proper values (e.g. by using 'ocis init --diff' and applying the patch or setting a value manually in the config/corresponding environment variable).
Nov 26 10:03:18 systemd[1]: owncloud.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 10:03:18 systemd[1]: owncloud.service: Failed with result 'exit-code'.
Nov 26 10:03:19 systemd[1]: owncloud.service: Scheduled restart job, restart counter is at 5.
Nov 26 10:03:19 systemd[1]: Stopped owncloud.service - ownCloud: Infinite Scale server.
Nov 26 10:03:19 systemd[1]: owncloud.service: Start request repeated too quickly.
Nov 26 10:03:19 systemd[1]: owncloud.service: Failed with result 'exit-code'.
Nov 26 10:03:19 systemd[1]: Failed to start owncloud.service - ownCloud: Infinite Scale server.`

**Comment by ericgaspar** [comment]
Strange... I had no problem with updating/installing ownCloud for a while now.
can you delete the app (also delete the data when deleting the app) and reinstall ownCloud.

PS please share your logs with the green button (share logs with YunoPast)

**Comment by Thelch** [comment]
Reinstalling was the key. Thanks for your help.
